import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import NavBar from "./NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// this root layout defines the common UI for all our pages
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // |exercise| you're going to want to put the nav in the body
    // i prefer to implement it in a separate component and use it here cause I don't want to dirty this shit up. keep it nice
    // add data-theme="dark" to html tag (note from the documentation)
    <html lang="en" data-theme="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* we can also create nested layouts, for example, if all our admin need a particular layout we can create a custom layout for our admin area  */}
        {/* we are rendering children here which can be a page at run time */}
        {/* first lets render our NavBar before children */}
        <NavBar />
        {/*render children in the main area*/}
        <main className="p-5">
          <Suspense>{children}</Suspense>
        </main>
      </body>
    </html>
  );
}
